- name: wordpress playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: preprovision-wordpress
  - role: helm-ansible-base
  - role: postprovision-wordpress
    playbook_debug: false
